#数据库连接
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/manage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

server:
  port: 8081
  
# mybatis包的扫描，还有就是映射文件设置 mybatis tk插件的使用
mybatis:
    type-aliases-package: package com.biqi.model
    mapper-locations: classpath:com.biqi.daoxml/*.xml
    
mapper:
    mappers:
        - com.common.mybatis.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
  
# Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#打印sql的日志
logging:
  level:
    com:
      biqi:
        dao: debug
